name: Running JEST-TESTS

on:
    pull_request:
        # push:
        branches:
            - main
    # schedule:
    #     - cron: '0 14 * * *'
jobs:
    test:
        name: Running Cypress Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install
              run: npm install
            - name: Test on chrome
              run: npm run test
